/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Connection.ConnectionService;
import javax.swing.JFileChooser;
import Global.CGlobals;
import javax.swing.JButton;
import Connection.*;

/**
 *
 * @author gamaa_000
 */
public class SettingsGUI extends javax.swing.JFrame
{

    JButton m_cachedDownloadBtn;
    JButton m_cachedSharedBtn;

    /**
     * Creates new form SettingsGUI
     */
    public SettingsGUI( JButton in_DownloadBtn, JButton in_SharedBtn )
    {
        m_cachedDownloadBtn = in_DownloadBtn;
        m_cachedSharedBtn = in_SharedBtn;

        if ( !CGlobals.m_strSharedDirPath.equals( "" ) && !CGlobals.m_strDownloadPath.equals( "" ) )
        {
            login.setEnabled( true );
        }
        initComponents();
    }

    public SettingsGUI()
    {
        if ( !CGlobals.m_strSharedDirPath.equals( "" ) && !CGlobals.m_strDownloadPath.equals( "" ) )
        {
            login.setEnabled( true );
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        login = new javax.swing.JButton();
        sharedDir = new javax.swing.JButton();
        downloadDir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        login.setText("Log In");
        login.setEnabled(false);
        login.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                loginActionPerformed(evt);
            }
        });

        sharedDir.setText("Shared Directory");
        sharedDir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sharedDirActionPerformed(evt);
            }
        });

        downloadDir.setText("Download Directory");
        downloadDir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                downloadDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(downloadDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sharedDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(login)
                .addGap(18, 18, 18)
                .addComponent(sharedDir)
                .addGap(18, 18, 18)
                .addComponent(downloadDir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_loginActionPerformed
    {//GEN-HEADEREND:event_loginActionPerformed
        m_cachedDownloadBtn.setEnabled( true );
        m_cachedSharedBtn.setEnabled( true );
        CFileService test = new CFileService();
        test.startFileService();
        //ConnectionService connection = new ConnectionService();
        //connection.findLeader();
        //TODO: check if it could connect to the leader.
        this.dispose();//not yet, after connection
        
    }//GEN-LAST:event_loginActionPerformed

    private void sharedDirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sharedDirActionPerformed
    {//GEN-HEADEREND:event_sharedDirActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory( new java.io.File(".") );
        jfc.setDialogTitle( "Select Shared Directory" );
        jfc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        
        if( jfc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION )
            CGlobals.m_strSharedDirPath = jfc.getSelectedFile().getPath() + "\\";
        
        if( !CGlobals.m_strSharedDirPath.equals("") && !CGlobals.m_strDownloadPath.equals("") )
            login.setEnabled( true );
    }//GEN-LAST:event_sharedDirActionPerformed

    private void downloadDirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_downloadDirActionPerformed
    {//GEN-HEADEREND:event_downloadDirActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory( new java.io.File(".") );
        jfc.setDialogTitle( "Select Download Directory" );
        jfc.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
        
        if( jfc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION )
            CGlobals.m_strDownloadPath = jfc.getSelectedFile().getPath() + "\\";
        
        if( !CGlobals.m_strSharedDirPath.equals("") && !CGlobals.m_strDownloadPath.equals("") )
            login.setEnabled( true );
    }//GEN-LAST:event_downloadDirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] )
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( SettingsGUI.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( SettingsGUI.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( SettingsGUI.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( SettingsGUI.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new SettingsGUI().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadDir;
    private javax.swing.JButton login;
    private javax.swing.JButton sharedDir;
    // End of variables declaration//GEN-END:variables
}
