package dms;


/**
* dms/RemoteServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Wednesday, April 5, 2017 7:20:01 PM CDT
*/

public interface RemoteServer extends RemoteServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteServer
