package dms;


/**
* dms/RemoteServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Wednesday, April 5, 2017 7:20:01 PM CDT
*/

public interface RemoteServerOperations 
{
  void GetFile (String fileName, dms.RemoteClient rCRef);
} // interface RemoteServerOperations
