package dms;


/**
* dms/RemoteClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Wednesday, April 5, 2017 7:20:01 PM CDT
*/

public interface RemoteClientOperations 
{
  void WriteFile (String fileName, byte[] data, int length);
} // interface RemoteClientOperations
