package dms;


/**
* dms/FileListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:20:10 AM CDT
*/

public final class FileListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public FileListHolder ()
  {
  }

  public FileListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dms.FileListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dms.FileListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dms.FileListHelper.type ();
  }

}
