package dms;

/**
* dms/RemoteLeaderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:19:52 AM CDT
*/

public final class RemoteLeaderHolder implements org.omg.CORBA.portable.Streamable
{
  public dms.RemoteLeader value = null;

  public RemoteLeaderHolder ()
  {
  }

  public RemoteLeaderHolder (dms.RemoteLeader initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dms.RemoteLeaderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dms.RemoteLeaderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dms.RemoteLeaderHelper.type ();
  }

}
