package dms;


/**
* dms/RemoteServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 7, 2017 12:10:22 PM CDT
*/

public interface RemoteServerOperations 
{
  void GetFile (String fileName, dms.RemoteClient rCRef);
} // interface RemoteServerOperations
