package dms;


/**
* dms/RemoteClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:19:52 AM CDT
*/

abstract public class RemoteClientHelper
{
  private static String  _id = "IDL:dms/RemoteClient:1.0";

  public static void insert (org.omg.CORBA.Any a, dms.RemoteClient that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static dms.RemoteClient extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (dms.RemoteClientHelper.id (), "RemoteClient");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static dms.RemoteClient read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemoteClientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, dms.RemoteClient value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static dms.RemoteClient narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dms.RemoteClient)
      return (dms.RemoteClient)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dms._RemoteClientStub stub = new dms._RemoteClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static dms.RemoteClient unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof dms.RemoteClient)
      return (dms.RemoteClient)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      dms._RemoteClientStub stub = new dms._RemoteClientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
