package dms;


/**
* dms/RemoteServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 7, 2017 5:35:11 PM CDT
*/

public interface RemoteServer extends RemoteServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteServer
