package dms;


/**
* dms/RemoteLeaderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 7, 2017 5:35:11 PM CDT
*/

public interface RemoteLeaderOperations 
{
  void update (String owner, String[] fileList);
} // interface RemoteLeaderOperations
