package dms;

/**
* dms/RemoteClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:20:10 AM CDT
*/

public final class RemoteClientHolder implements org.omg.CORBA.portable.Streamable
{
  public dms.RemoteClient value = null;

  public RemoteClientHolder ()
  {
  }

  public RemoteClientHolder (dms.RemoteClient initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dms.RemoteClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dms.RemoteClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dms.RemoteClientHelper.type ();
  }

}
