package dms;


/**
* dms/RemoteServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:20:10 AM CDT
*/

public interface RemoteServerOperations 
{
  void GetFile (String FileName, dms.RemoteClient rCRef);
} // interface RemoteServerOperations
