package dms;


/**
* dms/RemoteClient.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 7, 2017 12:10:22 PM CDT
*/

public interface RemoteClient extends RemoteClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemoteClient
