package dms;


/**
* dms/RemoteLeaderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:20:10 AM CDT
*/

public interface RemoteLeaderOperations 
{
  void update (String owner, String[] FileList);
} // interface RemoteLeaderOperations
