package dms;


/**
* dms/RemoteClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dms.idl
* Friday, April 28, 2017 9:19:52 AM CDT
*/

public interface RemoteClientOperations 
{
  void WriteFile (String fileName, byte[] data, int length, double fileLength);
} // interface RemoteClientOperations
